baseurl = "/"
languageCode = "en-us"
theme = "terminal"
paginate = 5

[params]
  contentTypeName = "post"
  themeColor = "pink"
  showMenuItems = 2
  fullWidthTheme = false
  centerTheme = true

[languages]
  [languages.en]
    title = "rie blog"
    subtitle = "some notes"
    keywords = "development linux blog"
    copyright = "© 2019-2020, rie."
    menuMore = "show more"
    readMore = "read more"
    readOtherPosts = "other posts"

    [languages.en.params.logo]
      logoText = "rie"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "about"
        url = "/about"
      # [[languages.en.menu.main]]
      #   identifier = "showcase"
      #   name = "Showcase"
      #   url = "/showcase"
